In [1]:
import pandas as pd

In [64]:
df = pd.read_csv('/Users/amos/Downloads/all_playoff_games.csv')

In [65]:
df['GAME_DATE'] = pd.to_datetime(df['GAME_DATE'])

In [66]:
df

,Unnamed: 0,SEASON_ID,TEAM_ID_A,TEAM_ABBREVIATION_A,TEAM_NAME_A,GAME_ID,GAME_DATE,MATCHUP_A,WL_A,MIN_A,...,FT_PCT_B,OREB_B,DREB_B,REB_B,AST_B,STL_B,BLK_B,TOV_B,PF_B,PLUS_MINUS_B
0,2,42021,1610612744,GSW,Golden State Warriors,42100405,2022-06-13,GSW vs. BOS,W,240,...,0.677,8,39,47,18,2,2,18,16,-10.0
1,6,42021,1610612738,BOS,Boston Celtics,42100404,2022-06-10,BOS vs. GSW,L,241,...,0.800,16,39,55,20,10,5,16,21,10.0
2,9,42021,1610612738,BOS,Boston Celtics,42100403,2022-06-08,BOS vs. GSW,W,240,...,0.867,6,25,31,22,7,5,16,23,-16.0
3,13,42021,1610612744,GSW,Golden State Warriors,42100402,2022-06-05,GSW vs. BOS,W,241,...,0.765,6,37,43,24,5,7,18,18,-19.0
4,17,42021,1610612744,GSW,Golden State Warriors,42100401,2022-06-02,GSW vs. BOS,L,241,...,0.813,7,32,39,33,7,6,12,13,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3034,12137,41983,1610612742,DAL,Dallas Mavericks,48300002,1984-04-17,DAL vs. SEA,W,240,...,0.833,6,30,36,19,8,5,9,22,NaN
3035,12142,41983,1610612765,DET,Detroit Pistons,48300004,1984-04-17,DET vs. NYK,L,240,...,0.786,17,26,43,20,13,7,15,20,NaN
3036,12146,41983,1610612762,UTH,Utah Jazz,48300003,1984-04-17,UTH vs. DEN,W,240,...,0.769,14,32,46,28,10,1,19,26,NaN
3037,12149,41983,1610612738,BOS,Boston Celtics,48300001,1984-04-17,BOS vs. WAS,W,240,...,0.800,9,30,39,23,4,3,17,26,NaN
3038,12154,41983,1610612749,MIL,Milwaukee Bucks,48300005,1984-04-17,MIL vs. ATL,W,240,...,0.707,13,27,40,20,9,7,18,14,NaN

#   CREATE COLUMN TO SHOW WHICH GAME IT IS IN THE SERIES (1-7)
#   ANOTHER COLUMN FOR SERIES RESULT
#   -- COLUMN FINALS (YES/NO) --